<a href="https://colab.research.google.com/github/Afzal786/Python_packages/blob/master/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy**

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object

* sophisticated (broadcasting) functions

* tools for integrating C/C++ and Fortran code

* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

**The Basics**

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes.

Importing **Numpy** package alias as np

In [0]:
import numpy as np


NumPy’s array class is called ndarray. It is also known by the alias array.

In [0]:
print(type(np.array([1,2,3,4,5,'hello'])))

x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


**ndarray.ndim**

the number of axes (dimensions) of the array.

**ndarray.shape**

the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

**ndarray.size**

the total number of elements of the array. This is equal to the product of the elements of shape.

**ndarray.dtype**

an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

**ndarray.itemsize**

the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

**ndarray.data**
the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.


In [0]:
a = np.arange(15)
print(a)
print("Shape : ",str(a.shape))
print("Dimension : ",str(a.ndim))
print("DType : ",str(a.dtype.name))
print("Itemsize : ",str(a.itemsize))
print("Array Size : ",str(a.size))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Shape :  (15,)
Dimension :  1
DType :  int64
Itemsize :  8
Array Size :  15


**Array Creation**

There are several ways to create arrays.

1. You can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

2. You can also create array using List

3. You can also create array of Complex type




In [0]:
a = np.array([2,3,4])

l = np.array(list([1,2,3,4,5]))

c = np.array( [ [1,2], [3,4] ], dtype=complex )

print("A : ")

print(a)

print("\nL : ")

print(l)

print("\nC : ")

print(c)


A : 
[2 3 4]

L : 
[1 2 3 4 5]

C : 
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [0]:
a = np.zeros( (3,4) )
b = np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified
c = np.empty( (2,3) )                                 # uninitialized, output may vary
print("A : ")

print(a)

print("\nB : ")

print(b)

print("\nC : ")

print(c)


A : 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

B : 
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

C : 
[[1.81773787e-316 2.96120023e-316 1.90658549e-316]
 [2.98428575e-316 4.96822067e-309 0.00000000e+000]]


To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.



In [0]:
np.arange( 10, 30, 5 )


array([10, 15, 20, 25])

In [0]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments


array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

In [0]:
from numpy import pi
a = np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)
print("A : ")

print(a)

print("\nX : ")

print(x)

print("\nF : ")

print(f)


A : 
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

X : 
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.331

**Printing Arrays**

When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

1. the last axis is printed from left to right,
2. the second-to-last is printed from top to bottom,
3. the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [0]:
a = np.arange(6)                         # 1d array
b = np.arange(12).reshape(4,3)           # 2d array
c = np.arange(24).reshape(2,3,4)         # 3d array


print("A : ")

print(a)

print("\nB : ")

print(b)

print("\nC : ")

print(c)


A : 
[0 1 2 3 4 5]

B : 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

C : 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [0]:
print(np.arange(10000))
print(np.arange(10000).reshape(100,100))


[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


**Basic Operations**

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [0]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
c = a-b
print("A : ")

print(a)

print("\nB : ")

print(b)

print("\nC : ")

print(c)

print("\n")
print(b**2)
print("\n")

print(10*np.sin(a))
print("\n")
print(a<35)


A : 
[20 30 40 50]

B : 
[0 1 2 3]

C : 
[20 29 38 47]


[0 1 4 9]


[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


[ True  True False False]


Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

In [0]:
A = np.array( [[1,1],
...             [0,1]] )
B = np.array( [[2,0],
...             [3,4]] )

print("elementwise product")
print(A * B)                       # elementwise product

print("matrix product")
print(A @ B)                       # matrix product

print("another matrix product")
print(A.dot(B))                    # another matrix product


elementwise product
[[2 0]
 [0 4]]
matrix product
[[5 4]
 [3 4]]
another matrix product
[[5 4]
 [3 4]]


Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [0]:
a = np.ones((2,3), dtype=int)
a *= 3
a


array([[3, 3, 3],
       [3, 3, 3]])

In [0]:
a = np.ones((2,3), dtype=int)
a *= 3
b = np.random.random((2,3))
b += a


Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [0]:
a = np.random.random((2,3))
a


array([[0.03213956, 0.41390405, 0.79071931],
       [0.01714967, 0.99985374, 0.66649699]])

In [0]:

a.max()


0.9998537440783191

In [0]:
a.min()


0.017149668639838578

In [0]:
a.sum()

2.9202633146342216

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [0]:
>>> b = np.arange(12).reshape(3,4)
print(b)
print("\nsum of each column : ")
print(b.sum(axis=0))                            # sum of each column
print("\nmin of each row")
print(b.min(axis=1))                            # min of each row
print("\ncumulative sum along each row")
print(b.cumsum(axis=1))                         # cumulative sum along each row


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

sum of each column : 
[12 15 18 21]

min of each row
[0 4 8]

cumulative sum along each row
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


**Universal Functions**

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output

In [0]:
B = np.arange(3)
print(B)
print(np.exp(B))


[0 1 2]
[1.         2.71828183 7.3890561 ]


In [0]:
np.sqrt(B)



array([0.        , 1.        , 1.41421356])

In [0]:
C = np.array([2., -1., 4.])
np.add(B, C)


array([2., 0., 6.])

Indexing, Slicing and Iterating
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [5]:
a =  np.arange(10)**2
print(a)
print("\n")
print(a[0:9]) #Slicing

[ 0  1  4  9 16 25 36 49 64 81]


[ 0  1  4  9 16 25 36 49 64]


In [7]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
print(a)

[-1000     1 -1000     9 -1000    25    36    49    64    81]


In [8]:
a[ : :-1]                                 # reversed a

array([   81,    64,    49,    36,    25, -1000,     9, -1000,     1,
       -1000])

**Multidimensional arrays** can have one index per axis. These indices are given in a tuple separated by commas:

In [10]:
def f(x,y):
...     return 10*x+y
...
b = np.fromfunction(f,(5,4),dtype=int)
print(b)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [14]:
print(b[2,3])

print(b[0:5, 1])                       # each row in the second column of b


23
[ 1 11 21 31 41]


In [12]:
b[ : ,1]                        # equivalent to the previous example


array([ 1, 11, 21, 31, 41])

In [11]:
b[1:3, : ]                      # each column in the second and third row of b


array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [15]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

x[1 , 2 , . . . ] is equivalent to x[1 , 2 , : , : , : ] ,

x[ . . . , 3] to x[ : , : , : , : , 3 ] and

x[4 , . . . , 5 , : ] to x[ 4 , : , : , 5 , :].

In [16]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
...                 [ 10, 12, 13]],
...                [[100,101,102],
...                 [110,112,113]]])
c.shape


(2, 2, 3)

In [17]:
c[1,...]                                   # same as c[1,:,:] or c[1]


array([[100, 101, 102],
       [110, 112, 113]])

In [18]:
c[...,2]                                   # same as c[:,:,2]


array([[  2,  13],
       [102, 113]])

In [19]:
for row in b:
...     print(row)
...

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


However, if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:

In [20]:
for element in b.flat:
...     print(element)
...

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


**Shape Manipulation**

An array has a shape given by the number of elements along each axis:

In [22]:
a = np.floor(10*np.random.random((3,4)))
print(a)
print("Shape : ")
a.shape

[[2. 2. 4. 5.]
 [4. 5. 4. 7.]
 [9. 7. 6. 0.]]
Shape : 


(3, 4)

The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

In [28]:
print("1. Flatten : ")
print(a.ravel())  # returns the array, flattened
print("2. Reshape : ")
print(a.reshape(6,2))  # returns the array with a modified shape
print("3. Transposed : ")
print(a.T)  # returns the array, transposed
print("4. Shape : ")
print(a.T.shape)
print("5. Shape : ")
print(a.shape)


1. Flatten : 
[2. 2. 4. 5. 4. 5. 4. 7. 9. 7. 6. 0.]
2. Reshape : 
[[2. 2.]
 [4. 5.]
 [4. 5.]
 [4. 7.]
 [9. 7.]
 [6. 0.]]
3. Transposed : 
[[2. 4. 9.]
 [2. 5. 7.]
 [4. 4. 6.]
 [5. 7. 0.]]
4. Shape : 
(4, 3)
5. Shape : 
(3, 4)


The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:

In [32]:
a = np.arange(12).reshape(3,4)
print("A : ")
print(a)

a.resize((2,6))
print("After Resizing ; ")
print(a)


A : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After Resizing ; 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [33]:
a = np.floor(10*np.random.random((2,2)))
print("A : ")
print(a)

b = np.floor(10*np.random.random((2,2)))
print("B : ")
print(b)

print("Vertical Stack : ")
print(np.vstack((a,b)))

print("Horizontal Stack : ")

print(np.hstack((a,b)))

A : 
[[1. 4.]
 [1. 6.]]
B : 
[[9. 1.]
 [3. 0.]]
Vertical Stack : 
[[1. 4.]
 [1. 6.]
 [9. 1.]
 [3. 0.]]
Horizontal Stack : 
[[1. 4. 9. 1.]
 [1. 6. 3. 0.]]


**Splitting one array into several smaller ones**

Using hsplit, you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur:

In [34]:
a = np.floor(10*np.random.random((2,12)))
a


array([[5., 9., 3., 7., 8., 9., 9., 3., 7., 7., 1., 3.],
       [6., 3., 7., 2., 4., 8., 6., 9., 7., 6., 8., 1.]])

In [35]:
np.hsplit(a,3)   # Split a into 3



[array([[5., 9., 3., 7.],
        [6., 3., 7., 2.]]), array([[8., 9., 9., 3.],
        [4., 8., 6., 9.]]), array([[7., 7., 1., 3.],
        [7., 6., 8., 1.]])]

In [36]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[5., 9., 3.],
        [6., 3., 7.]]), array([[7.],
        [2.]]), array([[8., 9., 9., 3., 7., 7., 1., 3.],
        [4., 8., 6., 9., 7., 6., 8., 1.]])]